

export const FETCH_ADS = 'FETCH_ADS';
export const FETCH_AD_BY_ID_SUCCESS = 'FETCH_AD_BY_ID_SUCCESS';
export const FETCH_AD_BY_ID_INIT = 'FETCH_AD_BY_ID_INIT';
export const FETCH_ADS_SUCCESS = 'FETCH_ADS_SUCCESS';


export const FETCH_USER_BOOKINGS_SUCCESS = 'FETCH_USER_BOOKINGS_SUCCESS';
export const FETCH_USER_BOOKINGS_FAIL = 'FETCH_USER_BOOKINGS_FAIL';
export const FETCH_USER_BOOKINGS_INIT = 'FETCH_USER_BOOKINGS_INIT';


export const FETCH_ADS_INIT = 'FETCH_ADS_INIT';
export const FETCH_ADS_FAIL = 'FETCH_ADS_FAIL';

export const UPDATE_AD_SUCCESS = 'UPDATE_AD_SUCCESS';
export const UPDATE_AD_FAIL = 'UPDATE_AD_FAIL';
export const RESET_AD_ERRORS = 'RESET_AD_ERRORS';


export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

export const RELOAD_MAP = 'RELOAD_MAP';
export const RELOAD_MAP_FINISH = 'RELOAD_MAP_FINISH';
